### ISSUE TITLE
Auto ID for CockroachDB breaks Pydantic

### ISSUE THREAD

**Issue by unownone** [tortoise/tortoise-orm#1365]
**Describe the bug**
If one tries to use cockroachdb along with `pydantic_model_creator()` breaks when you try to convert a model object using `Object.from_tortoise_orm(tortoise_object)`
This error is encountered:
```python
Apr 3 05:32:11 PM      return super().from_orm(obj)
Apr 3 05:32:11 PM             ^^^^^^^^^^^^^^^^^^^^^
Apr 3 05:32:11 PM    File "pydantic/main.py", line 579, in pydantic.main.BaseModel.from_orm
Apr 3 05:32:11 PM  pydantic.error_wrappers.ValidationError: 1 validation error for User
Apr 3 05:32:11 PM  id
Apr 3 05:32:11 PM    ensure this value is less than or equal to 2147483647 (type=value_error.number.not_le; limit_value=2147483647)
```

**To Reproduce**
Set up a Model that uses CockroachDB.
```python
class User(models.Model):
    """
    The User model
    """

    id = fields.IntField(pk=True)
    #: This is a email
    email = fields.CharField(max_length=50, unique=True)
    name = fields.CharField(max_length=50, null=True)
    password_hash = fields.CharField(max_length=128, null=True)
    created_at = fields.DatetimeField(auto_now_add=True)
    modified_at = fields.DatetimeField(auto_now=True)

    class Meta:
        table = "users"
        ordering = ["name"]

    class PydanticMeta:
        exclude = ["password_hash"]

    async def check_password(self, password: str) -> bool:
        return bcrypt.checkpw(
            password.encode("utf-8"), self.password_hash.encode("utf-8")
        )


# Pydantic models
User_Pydantic = pydantic_model_creator(User, name="User")
```
And then in a code try to create and return the `User_Pydantic` model :
```python
@auth_router.post("/signup")
async def signup(user: UserRequest):
    await user.hash_password()  # Hash the password
    user_obj = await User.create(**user.dict(exclude_unset=True))
    print(user_obj)
    return await User_Pydantic.from_tortoise_orm(user_obj)
```

**Expected behavior**
Expected behaviour would return the User_Pydantic value in response.

**Additional context**
Using this config:
```toml
[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.95.0"
openai = "^0.27.2"
uvicorn = "^0.21.1"
orjson = "^3.8.9"
python-multipart = "^0.0.6"
asyncpg = "^0.27.0"
psycopg2-binary = "^2.9.5"
fastapi-login = "^1.9.0"
tortoise-orm = {extras = ["asyncpg"], version = "^0.19.3"}
bcrypt = "^4.0.1"
pydantic = {extras = ["email"], version = "^1.10.7"}
aerich = "0.6.3"


[tool.poetry.scripts]
serve = "tuteai_backend:serve_dev"
serve-prod = "tuteai_backend:serve_prod"


[tool.poetry.group.dev.dependencies]
devtools = "^0.10.0"
alembic = "^1.10.2"
```
